apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-on-kubernetes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-spring-boot-on-kubernetes
  template:
    metadata:
      labels:
        app: demo-spring-boot-on-kubernetes
    spec:
      containers:
        - name: demo-spring-boot-on-kubernetes
          image: slartibartfast/demo-spring-boot-on-kubernetes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9595
