apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-on-kubernetes-service
spec:
  type: NodePort
  selector:
    app: demo-spring-boot-on-kubernetes
  ports:
    - targetPort: 9595
      port: 9595
      nodePort: 30095